const data = {
	// users: [
	// 	{
	// 		name: "Cengiz",
	// 		email: "admin@example.com",
	// 		password: bcrypt.hashSync("1234", 8),
	// 		isAdmin: true,
	// 	},
	// 	{
	// 		name: "Enes",
	// 		email: "user@example.com",
	// 		password: bcrypt.hashSync("1234", 8),
	// 		isAdmin: true,
	// 	},
	// ],
	products: [
		{
			name: "Fıstık 1",
			category: "Fıstık",
			image: "/assets/product/p2.jpeg",
			price: 120,
			countInStock: 10,
			brand: "Ala Fıstık",

			description: "İyi fıstık",
			ingredients: ["Karbonhidrat: 10gr", "Protein: 10gr", "Yağ: 10gr"],
			weight: "450gr",
			type: "Boz Fıstık",
		},
		{
			name: "Fıstık 2",
			category: "Fıstık",
			image: "/assets/product/p2.jpeg",
			price: 100,
			countInStock: 20,
			brand: "Ala Fıstık",

			description: "İyi fıstık",
			ingredients: ["Karbonhidrat: 10gr", "Protein: 10gr", "Yağ: 10gr"],
			weight: "450gr",
			type: "Boz Fıstık",
		},
		{
			name: "Fıstık 3",
			category: "Fıstık",
			image: "/assets/product/p3.jpeg",
			price: 220,
			countInStock: 0,
			brand: "Ala Fıstık",

			description: "İyi fıstık",
			ingredients: ["Karbonhidrat: 10gr", "Protein: 10gr", "Yağ: 10gr"],
			weight: "450gr",
			type: "Boz Fıstık",
		},
		{
			name: "Fıstık 4",
			category: "Fıstık",
			image: "/assets/product/p4.jpeg",
			price: 78,
			countInStock: 15,
			brand: "Ala Fıstık",

			description: "İyi fıstık",
			ingredients: ["Karbonhidrat: 10gr", "Protein: 10gr", "Yağ: 10gr"],
			weight: "450gr",
			type: "Boz Fıstık",
		},
		{
			name: "Fıstık 5",
			category: "Fıstık",
			image: "/assets/product/p5.jpeg",
			price: 65,
			countInStock: 5,
			brand: "Ala Fıstık",

			description: "İyi fıstık",
			ingredients: ["Karbonhidrat: 10gr", "Protein: 10gr", "Yağ: 10gr"],
			weight: "450gr",
			type: "İç Fıstık",
		},
		{
			name: "Fıstık 6",
			category: "Fıstık",
			image: "/assets/product/p6.jpeg",
			price: 139,
			countInStock: 12,
			brand: "Ala Fıstık",
			rating: 4.5,
			numReviews: 15,
			description: "İyi fıstık",
			ingredients: ["Karbonhidrat: 10gr", "Protein: 10gr", "Yağ: 10gr"],
			weight: "450gr",
			type: "İç Fıstık",
		},
		{
			name: "Fıstık 7",
			category: "Fıstık",
			image: "/assets/product/p7.jpeg",
			price: 139,
			countInStock: 12,
			brand: "Ala Fıstık",

			description: "İyi fıstık",
			ingredients: ["Karbonhidrat: 10gr", "Protein: 10gr", "Yağ: 10gr"],
			weight: "450gr",
			type: "Boz Fıstık",
		},
		{
			name: "Fıstık 8",
			category: "Fıstık",
			image: "/assets/product/p8.jpeg",
			price: 139,
			countInStock: 12,
			brand: "Ala Fıstık",

			description: "İyi fıstık",
			ingredients: ["Karbonhidrat: 10gr", "Protein: 10gr", "Yağ: 10gr"],
			weight: "450gr",
			type: "İç Fıstık",
		},

		{
			name: "Fıstık 9",
			category: "Fıstık",
			image: "/assets/product/p9.jpeg",
			price: 139,
			countInStock: 12,
			brand: "Ala Fıstık",

			description: "İyi fıstık",
			ingredients: ["Karbonhidrat: 10gr", "Protein: 10gr", "Yağ: 10gr"],
			weight: "450gr",
			type: "İç Fıstık",
		},
	],
};
export default data;
